name: remote ssh command
on: [push]
jobs:

  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT }}
        password: ${{ secrets.ROOT_PASSWORD }}
        script: sudo chmod a+x -R /var/www/lelandbove27.site/public_html/cgibin 